const programmingLanguages = [
  { name: "JavaScript", short: "JS", environment: "Web / Node.js" },
  { name: "Python", short: "PY", environment: "CLI / Server / Data Science" },
  { name: "Java", short: "JAVA", environment: "JVM / Android" },
  { name: "C++", short: "CPP", environment: "Desktop / Embedded / Game Dev" },
  { name: "C#", short: "CS", environment: ".NET / Windows / Unity" },
  { name: "PHP", short: "PHP", environment: "Web Server" },
  { name: "Go", short: "GO", environment: "Server / Cloud / CLI" },
  { name: "Rust", short: "RS", environment: "System / WebAssembly" },
  { name: "TypeScript", short: "TS", environment: "Web / Node.js" },
  { name: "Kotlin", short: "KT", environment: "JVM / Android" },
  { name: "Swift", short: "SW", environment: "iOS / macOS" },
  { name: "Ruby", short: "RB", environment: "Web / CLI" },
  { name: "Scala", short: "SC", environment: "JVM / Server / Data" },
  { name: "Haskell", short: "HS", environment: "CLI / Server / FP" },
  { name: "Elixir", short: "EX", environment: "BEAM / Phoenix / Realtime" },
  { name: "Erlang", short: "ERL", environment: "BEAM / Telecom / Realtime" },
  { name: "Dart", short: "DART", environment: "Web / Flutter" },
  { name: "Julia", short: "JL", environment: "Scientific / CLI" },
  { name: "R", short: "R", environment: "Data Science / Stats" },
  { name: "Bash", short: "BASH", environment: "Shell / Scripting" },
  { name: "C", short: "C", environment: "Systems / Embedded" },
  { name: "MATLAB", short: "MAT", environment: "Engineering / Scientific" },
  { name: "Perl", short: "PL", environment: "CLI / Web legacy" },
  { name: "Lua", short: "LUA", environment: "Embedded / Game Dev" },
  { name: "SQL", short: "SQL", environment: "Databases / Query Language" },
  { name: "Assembly", short: "ASM", environment: "Low-level / Embedded" },
  { name: "COBOL", short: "COB", environment: "Legacy / Mainframes" },
  { name: "Fortran", short: "F", environment: "Scientific / HPC" },
  { name: "PowerShell", short: "PS", environment: "Windows / DevOps" },
  { name: "Shell", short: "SH", environment: "Unix / Automation" },
  { name: "Objective-C", short: "OBJC", environment: "iOS / macOS legacy" },
  { name: "VB.NET", short: "VB", environment: ".NET / Legacy Apps" },
];

export default programmingLanguages;
